name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  api-tests:
    name: Run Postman API Tests (Newman)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Newman
        run: npm i -g newman

      - name: Run Postman collection against deployed API
        run: |
          newman run "postman/DemoAPIs.postman_collection.json" \
            --environment "postman/Local Param API.postman_environment.json" \
            --env-var "baseUrl=https://param-app.onrender.com" \
            --reporters cli

  deploy-backend:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    needs: [ api-tests ]
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

  deploy-frontend:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    needs: [ api-tests ]
    steps:
      - name: Vercel Auto Deploy
        run: echo "Vercel deploys automatically!"
